---
version: '2'

services:
  zcashd:
    image: gcr.io/zcash-web/zcashd:latest
    volumes:
      - $ZCASHD_DATADIR:/srv/zcashd/.zcash
      - $ZCASHD_PARMDIR:/srv/zcashd/.zcash-params
    environment:
      - ZCASHD_RPCUSER=$ZCASHD_RPCUSER
      - ZCASHD_RPCPASSWORD=$ZCASHD_RPCPASSWORD
      - ZCASHD_NETWORK=$ZCASHD_NETWORK
      - ZCASHD_ALLOWIP=$ZCASHD_ALLOWIP
    mem_limit: 4G
    ports:
      - "8232:8232"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  zcashd_exporter:
    build: .
    environment:
      - ZCASHD_RPCUSER=$ZCASHD_RPCUSER
      - ZCASHD_RPCPASSWORD=$ZCASHD_RPCPASSWORD
    command:
      - --rpc.host=zcashd
      - --rpc.port=8232
      - --rpc.user=$ZCASHD_RPCUSER
      - --rpc.password=$ZCASHD_RPCPASSWORD
    ports:
      - "9100:9100"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  grafana:
    image: grafana/grafana:6.4.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=$GF_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_ADMIN_PASSWORD
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  prometheus:
    image: prom/prometheus:v2.13.1
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - promethus_data:/promethus_data
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  loki:
    image: grafana/loki:master
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

volumes:
  promethus_data:
