{
 "title": "Zcashd node exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Local node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wallet Balance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "targets": [
    { "expr": "zcash_wallet_balance", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Blocks processed in the server",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "zcash_blocks" }
   ]
  },
  {
   "title": "Verification Progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    { "expr": "zcash_verification_progress" }
   ]
  },
  {
   "title": "Local node logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "zcashd logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{container_name=\"zcashd_exporter_zcashd_1\"}"
      }
     ]
    }
   ]
  },
  { "title": "Peer info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Peer traffic, recv/sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(zcash_peer_bytes_recv[1m])",
     "legendFormat": "{{ addr }} - {{ subver }} recv"
    },
    {
     "expr": "rate(zcash_peer_bytes_sent[1m])",
     "legendFormat": "{{ addr }} - {{ subver }} sent"
    }
   ]
  },
  {
   "title": "Peer versions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(zcash_peer_version == 170008)",
     "legendFormat": "170008"
    },
    {
     "expr": "count(zcash_peer_version == 170009)",
     "legendFormat": "170009"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Mempool Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "zcash_mempool_bytes" }
   ]
  },
  {
   "title": "Current tx count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 20 },
   "targets": [
    { "expr": "zcash_mempool_size" }
   ]
  }
 ]
}